import figlet from "figlet";
import { writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FONT = "Small";

// Map of key -> display text for the ASCII art
const commands = {
  help: "Help",
  about: "About",
  projects: "Projects",
  skills: "Skills",
  contact: "Contact",
  education: "Education",
  experience: "Experience",
  certs: "Certs",
  date: "Date",
};

const entries = Object.entries(commands).map(([key, label]) => {
  const art = figlet.textSync(label, { font: FONT });
  // Indent each line and trim trailing whitespace
  const lines = art
    .split("\n")
    .filter((l, i, arr) => i < arr.length - 1 || l.trim() !== "")
    .map((l) => {
      // Escape backslashes so the output is valid TypeScript
      const escaped = l.replaceAll("\\", "\\\\");
      return `    "  ${escaped}"`;
    })
    .join(",\n");

  return `  ${key}: [\n${lines},\n  ]`;
});

const output = `// ──────────────────────────────────────────────────
// Auto-generated by: npm run generate:ascii
// Font: ${FONT}
// Do not edit manually -- re-run the script instead.
// ──────────────────────────────────────────────────

export const asciiArt: Record<string, string[]> = {
${entries.join(",\n")},
};
`;

const outPath = resolve(__dirname, "../src/lib/asciiArt.ts");
writeFileSync(outPath, output);
console.log(`Generated ${outPath} (font: ${FONT})`);
